package pe.org.farmanova.moduloatencion.presentation.JFrame;

import java.awt.CardLayout;
import java.awt.Toolkit;
import java.time.DateTimeException;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pe.org.farmanova.moduloatencion.business.entities.Cliente;
import pe.org.farmanova.moduloatencion.business.entities.DetalleVenta;
import pe.org.farmanova.moduloatencion.business.entities.Medicamento;
import pe.org.farmanova.moduloatencion.business.entities.Turno;
import pe.org.farmanova.moduloatencion.business.entities.Venta;
import pe.org.farmanova.moduloatencion.business.enums.EstadoTurno;
import pe.org.farmanova.moduloatencion.business.enums.PrioridadTurno;
import pe.org.farmanova.moduloatencion.business.sesion.Sesion;
import pe.org.farmanova.moduloatencion.service.BusinessException;
import pe.org.farmanova.moduloatencion.service.ClienteService;
import pe.org.farmanova.moduloatencion.service.MedicamentoService;
import pe.org.farmanova.moduloatencion.service.TurnoService;
import pe.org.farmanova.moduloatencion.service.VentaService;

public class CajeroJFrame extends javax.swing.JFrame {

    private Cliente clienteVenta;
    private Medicamento medicamentoActual;
    private Venta ventaActual;

    public CajeroJFrame() {
        initComponents();
        lblCajero.setText(
                Sesion.getUsuarioActual().getUsuario()
        );

        limpiarFormulario();
        cargarTablaCliente();
        cargarTablaMedicamentos();
        actualizarHistorial();
        actualizarCola();
        this.setSize(977, 650);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        barraNavegadora = new javax.swing.JPanel();
        título = new javax.swing.JLabel();
        subtítulo = new javax.swing.JLabel();
        botonTurnos = new javax.swing.JButton();
        botonVentas = new javax.swing.JButton();
        botonClientes = new javax.swing.JButton();
        botonCerrar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        botonMedicamentos = new javax.swing.JButton();
        Contenido = new javax.swing.JPanel();
        Turnos = new javax.swing.JPanel();
        gestionTurno = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        botonNuevoTurno = new javax.swing.JButton();
        botonAtenderTurno = new javax.swing.JButton();
        cboFiltroEstado = new javax.swing.JComboBox<>();
        visualTurnos = new javax.swing.JPanel();
        PanelTurnos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTurnos = new javax.swing.JTable();
        buscarTurno = new javax.swing.JToggleButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        txtbuscarTurnoCodigo = new javax.swing.JTextPane();
        jLabel34 = new javax.swing.JLabel();
        nuevoTurno = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtDni = new javax.swing.JTextField();
        crearTurno = new javax.swing.JButton();
        cboHora = new javax.swing.JComboBox<>();
        cboPrioridad = new javax.swing.JComboBox<>();
        cboDia = new javax.swing.JComboBox<>();
        cboMes = new javax.swing.JComboBox<>();
        cboAnio = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        lblErrorDni = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        atenderTurno = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        atenderTurnos = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCola = new javax.swing.JTable();
        cancelarTurno = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        Clientes = new javax.swing.JPanel();
        gestionCliente = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        botonBuscarCliente = new javax.swing.JButton();
        visualClientes = new javax.swing.JPanel();
        listaClientes = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblCliente = new javax.swing.JTable();
        txtDniBuscar = new javax.swing.JTextField();
        buscarDni = new javax.swing.JButton();
        lblerrorDniBuscar = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        nuevoCliente = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        NombreCliente = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        DNICliente = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        TelefonoCliente = new javax.swing.JTextField();
        agregarCliente = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        ApellidoCliente = new javax.swing.JTextField();
        lblErrorDni2 = new javax.swing.JLabel();
        lblErrorTelefono = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        botonNuevoCliente1 = new javax.swing.JButton();
        jLabel61 = new javax.swing.JLabel();
        Medicamentos = new javax.swing.JPanel();
        gestionMedicamento = new javax.swing.JPanel();
        visualMedicamentos = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblMedicamentos = new javax.swing.JTable();
        btnBuscarMedicamento = new javax.swing.JButton();
        txtCodigoMedicamento = new javax.swing.JTextField();
        txtCodigoMedicamento.putClientProperty("JTextField.placeholderText", "Ingresa el código del medicamento");
        txtCodigoMedicamento.putClientProperty("JTextField.placeholderState", "clipped");
        txtCodigoMedicamento.putClientProperty("JTextField.arc", 15);
        jLabel24 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        Ventas = new javax.swing.JPanel();
        gestionVenta = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        visualVentas = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblDetalleVenta = new javax.swing.JTable();
        lblNombreCliente = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtDniCliente = new javax.swing.JTextPane();
        btnBuscarMedicamento2 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        lblCajero = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtCodigo = new javax.swing.JTextPane();
        btnBuscarCliente = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        lblNombreMedicamento = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        lblPrecioMedicamento = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        lblStockMedicamento = new javax.swing.JLabel();
        spCantidad = new javax.swing.JSpinner();
        jLabel33 = new javax.swing.JLabel();
        lblTotalPago = new javax.swing.JLabel();
        finalizarVenta = new javax.swing.JButton();
        agregarVenta = new javax.swing.JButton();
        quitarMedicamento = new javax.swing.JButton();
        cancelarVenta = new javax.swing.JButton();
        dniventaconf = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel2.setMaximumSize(new java.awt.Dimension(2694, 1660));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        barraNavegadora.setBackground(new java.awt.Color(228, 239, 255));
        barraNavegadora.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        título.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        título.setForeground(new java.awt.Color(0, 98, 196));
        título.setText("Farmanova");
        barraNavegadora.add(título, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        subtítulo.setForeground(new java.awt.Color(15, 116, 149));
        subtítulo.setText("Sistema de gestión integral");
        barraNavegadora.add(subtítulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, -1));

        botonTurnos.setBackground(new java.awt.Color(0, 114, 255));
        botonTurnos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonTurnos.setForeground(new java.awt.Color(255, 255, 255));
        botonTurnos.setText("Turnos");
        botonTurnos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonTurnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTurnosActionPerformed(evt);
            }
        });
        barraNavegadora.add(botonTurnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 170, 40));

        botonVentas.setBackground(new java.awt.Color(0, 114, 255));
        botonVentas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonVentas.setForeground(new java.awt.Color(255, 255, 255));
        botonVentas.setText("Ventas");
        botonVentas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVentasActionPerformed(evt);
            }
        });
        barraNavegadora.add(botonVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 170, 40));

        botonClientes.setBackground(new java.awt.Color(0, 114, 255));
        botonClientes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonClientes.setForeground(new java.awt.Color(255, 255, 255));
        botonClientes.setText("Clientes");
        botonClientes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonClientesActionPerformed(evt);
            }
        });
        barraNavegadora.add(botonClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 170, 40));

        botonCerrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonCerrar.setForeground(new java.awt.Color(255, 0, 0));
        botonCerrar.setText("Cerrar sesión");
        botonCerrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrarActionPerformed(evt);
            }
        });
        barraNavegadora.add(botonCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 170, 40));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/org/farmanova/moduloatencion/presentation/icons/iconFarmaciasSinFondo.png"))); // NOI18N
        barraNavegadora.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, 90));

        botonMedicamentos.setBackground(new java.awt.Color(0, 114, 255));
        botonMedicamentos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonMedicamentos.setForeground(new java.awt.Color(255, 255, 255));
        botonMedicamentos.setText("Medicamentos");
        botonMedicamentos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonMedicamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMedicamentosActionPerformed(evt);
            }
        });
        barraNavegadora.add(botonMedicamentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 170, 40));

        jPanel2.add(barraNavegadora, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 276, 610));

        Contenido.setLayout(new java.awt.CardLayout());

        gestionTurno.setBackground(new java.awt.Color(26, 136, 255));
        gestionTurno.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Gestión de Turnos");
        gestionTurno.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 6, -1, 50));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Atención por orden de llegada, priorizando emergencias y mayores");
        gestionTurno.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 62, 430, -1));

        botonNuevoTurno.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonNuevoTurno.setForeground(new java.awt.Color(0, 114, 255));
        botonNuevoTurno.setText("Nuevo Turno");
        botonNuevoTurno.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonNuevoTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevoTurnoActionPerformed(evt);
            }
        });
        gestionTurno.add(botonNuevoTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 127, -1));

        botonAtenderTurno.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonAtenderTurno.setForeground(new java.awt.Color(0, 114, 255));
        botonAtenderTurno.setText("Atender Turno");
        botonAtenderTurno.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonAtenderTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAtenderTurnoActionPerformed(evt);
            }
        });
        gestionTurno.add(botonAtenderTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, -1, -1));

        cboFiltroEstado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cboFiltroEstado.setForeground(new java.awt.Color(0, 114, 255));
        cboFiltroEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TODOS", "PENDIENTE", "ATENDIDO", "NO_VINO" }));
        cboFiltroEstado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cboFiltroEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboFiltroEstadoActionPerformed(evt);
            }
        });
        gestionTurno.add(cboFiltroEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        visualTurnos.setLayout(new java.awt.CardLayout());

        PanelTurnos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblTurnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "DNI", "Cliente", "Fecha", "Hora", "Prioridad", "Estado"
            }
        ));
        jScrollPane1.setViewportView(tblTurnos);

        PanelTurnos.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 630, 370));

        buscarTurno.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buscarTurno.setText("Buscar Turno");
        buscarTurno.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buscarTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarTurnoActionPerformed(evt);
            }
        });
        PanelTurnos.add(buscarTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, -1));

        jScrollPane8.setViewportView(txtbuscarTurnoCodigo);

        PanelTurnos.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 100, -1));

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 114, 255));
        jLabel34.setText("HISTORIAL DE TURNOS REGISTRADOS");
        PanelTurnos.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        visualTurnos.add(PanelTurnos, "cardTabla");

        nuevoTurno.setToolTipText("");
        nuevoTurno.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Prioridad:");
        nuevoTurno.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 110, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Cliente DNI:");
        nuevoTurno.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 110, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Fecha:");
        nuevoTurno.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 60, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Hora:");
        nuevoTurno.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 110, 30));

        txtDni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDniKeyTyped(evt);
            }
        });
        nuevoTurno.add(txtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 300, 30));

        crearTurno.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        crearTurno.setText("Agregar Turno");
        crearTurno.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        crearTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearTurnoActionPerformed(evt);
            }
        });
        nuevoTurno.add(crearTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, -1, -1));

        cboHora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "08:00", "08:15", "08:30", "08:45", "09:00", "09:15", "09:30", "09:45", "10:00", "10:15", "10:30", "10:45", "11:00", "11:15", "11:30", "11:45", "12:00", "12:15", "12:30", "12:45", "13:00", "13:15", "13:30", "13:45", "14:00", "14:15", "14:30", "14:45", "15:00", "15:15", "15:30", "15:45", "16:00", "16:15", "16:30", "16:45", "17:00", "17:15", "17:30", "17:45", "18:00", "18:15", "18:30", "18:45", "19:00", "19:15", "19:30", "19:45", "20:00", "20:15", "20:30", "20:45" }));
        nuevoTurno.add(cboHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 300, 30));

        cboPrioridad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NORMAL", "ADULTO_MAYOR", "EMERGENCIA" }));
        nuevoTurno.add(cboPrioridad, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 300, 30));

        cboDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        nuevoTurno.add(cboDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 50, 20));

        cboMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        nuevoTurno.add(cboMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 60, 20));

        cboAnio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2026", "2027", "2028", "2029", "2030" }));
        nuevoTurno.add(cboAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 70, 20));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setText("Año");
        nuevoTurno.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, -1, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setText("Día");
        nuevoTurno.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, -1, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setText("Mes");
        nuevoTurno.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, -1, -1));

        lblErrorDni.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblErrorDni.setForeground(new java.awt.Color(255, 51, 0));
        nuevoTurno.add(lblErrorDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 190, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 114, 255));
        jLabel3.setText("REGISTRAR NUEVO TURNO");
        nuevoTurno.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/org/farmanova/moduloatencion/presentation/icons/icnoAgregar.png"))); // NOI18N
        nuevoTurno.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 30, 40));

        visualTurnos.add(nuevoTurno, "cardNuevoTurno");

        atenderTurno.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 114, 255));
        jLabel8.setText("TURNOS REGISTRADOS PARA HOY");
        atenderTurno.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 310, 30));

        atenderTurnos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        atenderTurnos.setForeground(new java.awt.Color(0, 114, 255));
        atenderTurnos.setText("Atender Turno");
        atenderTurnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atenderTurnosActionPerformed(evt);
            }
        });
        atenderTurno.add(atenderTurnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, -1));

        tblCola.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Pacientes", "DNI", "Prioridad", "Fecha", "Hora"
            }
        ));
        jScrollPane2.setViewportView(tblCola);

        atenderTurno.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 630, 340));

        cancelarTurno.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cancelarTurno.setForeground(new java.awt.Color(255, 0, 51));
        cancelarTurno.setText("Ausente");
        cancelarTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarTurnoActionPerformed(evt);
            }
        });
        atenderTurno.add(cancelarTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 400, 90, -1));

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/org/farmanova/moduloatencion/presentation/icons/iconLista.png"))); // NOI18N
        atenderTurno.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        visualTurnos.add(atenderTurno, "cardAtenderTurno");

        gestionTurno.add(visualTurnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 650, 450));

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/org/farmanova/moduloatencion/presentation/icons/iconTurno.png"))); // NOI18N
        gestionTurno.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 12, -1, 40));

        javax.swing.GroupLayout TurnosLayout = new javax.swing.GroupLayout(Turnos);
        Turnos.setLayout(TurnosLayout);
        TurnosLayout.setHorizontalGroup(
            TurnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TurnosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gestionTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1697, Short.MAX_VALUE))
        );
        TurnosLayout.setVerticalGroup(
            TurnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TurnosLayout.createSequentialGroup()
                .addComponent(gestionTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1049, Short.MAX_VALUE))
        );

        Contenido.add(Turnos, "cardTurnos");

        Clientes.setMinimumSize(new java.awt.Dimension(600, 520));

        gestionCliente.setBackground(new java.awt.Color(26, 136, 255));
        gestionCliente.setMinimumSize(new java.awt.Dimension(600, 520));
        gestionCliente.setPreferredSize(new java.awt.Dimension(600, 520));
        gestionCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Gestión de Clientes");
        gestionCliente.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 6, -1, 50));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 3, 13)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Registro de clientes: Nombre completo, DNI y celular");
        gestionCliente.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 62, 430, -1));

        botonBuscarCliente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonBuscarCliente.setForeground(new java.awt.Color(0, 114, 255));
        botonBuscarCliente.setText("Lista de Clientes");
        botonBuscarCliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarClienteActionPerformed(evt);
            }
        });
        gestionCliente.add(botonBuscarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        visualClientes.setLayout(new java.awt.CardLayout());

        listaClientes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "DNI", "Nombre", "Apellido", "Telefono"
            }
        ));
        tblCliente.setName(""); // NOI18N
        jScrollPane6.setViewportView(tblCliente);

        listaClientes.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 630, 360));

        txtDniBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDniBuscarActionPerformed(evt);
            }
        });
        txtDniBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDniBuscarKeyTyped(evt);
            }
        });
        listaClientes.add(txtDniBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 130, 20));

        buscarDni.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buscarDni.setText("Buscar");
        buscarDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarDniActionPerformed(evt);
            }
        });
        listaClientes.add(buscarDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 110, 20));

        lblerrorDniBuscar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblerrorDniBuscar.setForeground(new java.awt.Color(255, 0, 0));
        listaClientes.add(lblerrorDniBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 210, 20));

        jLabel39.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(0, 114, 255));
        jLabel39.setText("LISTA DE NUESTROS CLIENTES");
        listaClientes.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 270, 30));

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/org/farmanova/moduloatencion/presentation/icons/iconLista.png"))); // NOI18N
        listaClientes.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        visualClientes.add(listaClientes, "cardListaCliente");

        nuevoCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 114, 255));
        jLabel12.setText("REGISTRAR NUEVO CLIENTE");
        nuevoCliente.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, -1, -1));
        nuevoCliente.add(NombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 300, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setText("Nombre:");
        nuevoCliente.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 110, 20));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setText("DNI:");
        nuevoCliente.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 110, 20));

        DNICliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                DNIClienteKeyTyped(evt);
            }
        });
        nuevoCliente.add(DNICliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 160, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setText("Telefono:");
        nuevoCliente.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 110, 20));

        TelefonoCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TelefonoClienteKeyTyped(evt);
            }
        });
        nuevoCliente.add(TelefonoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 160, -1));

        agregarCliente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        agregarCliente.setText("Agregar Cliente");
        agregarCliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        agregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarClienteActionPerformed(evt);
            }
        });
        nuevoCliente.add(agregarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, -1, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel21.setText("Apellido:");
        nuevoCliente.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 110, 20));
        nuevoCliente.add(ApellidoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 300, -1));

        lblErrorDni2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblErrorDni2.setForeground(new java.awt.Color(255, 51, 51));
        nuevoCliente.add(lblErrorDni2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 210, 20));

        lblErrorTelefono.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblErrorTelefono.setForeground(new java.awt.Color(255, 51, 51));
        nuevoCliente.add(lblErrorTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 290, 20));

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/org/farmanova/moduloatencion/presentation/icons/icnoAgregar.png"))); // NOI18N
        nuevoCliente.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, -1));

        visualClientes.add(nuevoCliente, "cardNuevoCliente");

        gestionCliente.add(visualClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 650, 450));

        botonNuevoCliente1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonNuevoCliente1.setForeground(new java.awt.Color(0, 114, 255));
        botonNuevoCliente1.setText("Nuevo Cliente");
        botonNuevoCliente1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonNuevoCliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevoCliente1ActionPerformed(evt);
            }
        });
        gestionCliente.add(botonNuevoCliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 150, -1));

        jLabel61.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/org/farmanova/moduloatencion/presentation/icons/iconClientes.png"))); // NOI18N
        gestionCliente.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 12, -1, 40));

        javax.swing.GroupLayout ClientesLayout = new javax.swing.GroupLayout(Clientes);
        Clientes.setLayout(ClientesLayout);
        ClientesLayout.setHorizontalGroup(
            ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClientesLayout.createSequentialGroup()
                .addComponent(gestionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1734, Short.MAX_VALUE))
        );
        ClientesLayout.setVerticalGroup(
            ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClientesLayout.createSequentialGroup()
                .addComponent(gestionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1037, Short.MAX_VALUE))
        );

        gestionCliente.getAccessibleContext().setAccessibleName("");

        Contenido.add(Clientes, "cardClientes");

        Medicamentos.setMaximumSize(new java.awt.Dimension(1920, 1369));
        Medicamentos.setMinimumSize(new java.awt.Dimension(1920, 1369));

        gestionMedicamento.setBackground(new java.awt.Color(26, 136, 255));
        gestionMedicamento.setMaximumSize(new java.awt.Dimension(683, 573));
        gestionMedicamento.setMinimumSize(new java.awt.Dimension(683, 573));
        gestionMedicamento.setPreferredSize(new java.awt.Dimension(683, 573));
        gestionMedicamento.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        visualMedicamentos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblMedicamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Precio", "Laboratorio", "Stock", "Vencimiento"
            }
        ));
        jScrollPane3.setViewportView(tblMedicamentos);
        if (tblMedicamentos.getColumnModel().getColumnCount() > 0) {
            tblMedicamentos.getColumnModel().getColumn(5).setHeaderValue("Vencimiento");
        }

        visualMedicamentos.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 630, 390));

        btnBuscarMedicamento.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBuscarMedicamento.setText("Buscar");
        btnBuscarMedicamento.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBuscarMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarMedicamentoActionPerformed(evt);
            }
        });
        visualMedicamentos.add(btnBuscarMedicamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 80, 20));

        txtCodigoMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoMedicamentoActionPerformed(evt);
            }
        });
        visualMedicamentos.add(txtCodigoMedicamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 120, 20));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 102, 255));
        jLabel24.setText("INVENTARIO DE MEDICAMENTOS");
        visualMedicamentos.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/org/farmanova/moduloatencion/presentation/icons/iconoBuscar.png"))); // NOI18N
        visualMedicamentos.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        gestionMedicamento.add(visualMedicamentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 650, 500));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Gestión de Medicamentos");
        gestionMedicamento.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 6, -1, 50));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 3, 13)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Buscar y ver medicamentos");
        gestionMedicamento.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 62, 430, -1));

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/org/farmanova/moduloatencion/presentation/icons/iconMedicamento.png"))); // NOI18N
        gestionMedicamento.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 12, -1, 40));

        javax.swing.GroupLayout MedicamentosLayout = new javax.swing.GroupLayout(Medicamentos);
        Medicamentos.setLayout(MedicamentosLayout);
        MedicamentosLayout.setHorizontalGroup(
            MedicamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MedicamentosLayout.createSequentialGroup()
                .addComponent(gestionMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1723, Short.MAX_VALUE))
        );
        MedicamentosLayout.setVerticalGroup(
            MedicamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MedicamentosLayout.createSequentialGroup()
                .addComponent(gestionMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1049, Short.MAX_VALUE))
        );

        Contenido.add(Medicamentos, "cardMedicamentos");

        Ventas.setMaximumSize(new java.awt.Dimension(1920, 1369));
        Ventas.setMinimumSize(new java.awt.Dimension(1920, 1369));

        gestionVenta.setBackground(new java.awt.Color(26, 136, 255));
        gestionVenta.setMaximumSize(new java.awt.Dimension(683, 573));
        gestionVenta.setMinimumSize(new java.awt.Dimension(683, 573));
        gestionVenta.setPreferredSize(new java.awt.Dimension(683, 573));
        gestionVenta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Gestión de Ventas");
        gestionVenta.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 50));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 3, 13)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Realiza ventas");
        gestionVenta.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 430, -1));

        visualVentas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblDetalleVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Medicamento", "Precio", "Cantidad", "SubTotal"
            }
        ));
        jScrollPane4.setViewportView(tblDetalleVenta);

        visualVentas.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 630, 200));

        lblNombreCliente.setBackground(new java.awt.Color(255, 255, 255));
        lblNombreCliente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNombreCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        visualVentas.add(lblNombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 260, 20));

        txtDniCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtDniCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDniClienteKeyTyped(evt);
            }
        });
        jScrollPane5.setViewportView(txtDniCliente);

        visualVentas.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 100, -1));

        btnBuscarMedicamento2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBuscarMedicamento2.setText("Buscar");
        btnBuscarMedicamento2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBuscarMedicamento2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarMedicamento2ActionPerformed(evt);
            }
        });
        visualVentas.add(btnBuscarMedicamento2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 70, 20));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel25.setText("Nombre:");
        visualVentas.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 70, -1));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel26.setText("Cliente:");
        visualVentas.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 60, -1));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel27.setText("Atendido por:");
        visualVentas.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 100, -1));

        lblCajero.setBackground(new java.awt.Color(255, 255, 255));
        lblCajero.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCajero.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        visualVentas.add(lblCajero, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 260, 20));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel28.setText("Cliente DNI:");
        visualVentas.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 90, -1));

        txtCodigo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane7.setViewportView(txtCodigo);

        visualVentas.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 70, -1));

        btnBuscarCliente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBuscarCliente.setText("Buscar");
        btnBuscarCliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });
        visualVentas.add(btnBuscarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 70, 20));

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel29.setText("ID Medicamento:");
        visualVentas.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 120, -1));

        lblNombreMedicamento.setBackground(new java.awt.Color(255, 255, 255));
        lblNombreMedicamento.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNombreMedicamento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        visualVentas.add(lblNombreMedicamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 260, 20));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel30.setText("Precio:");
        visualVentas.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 70, -1));

        lblPrecioMedicamento.setBackground(new java.awt.Color(255, 255, 255));
        lblPrecioMedicamento.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPrecioMedicamento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        visualVentas.add(lblPrecioMedicamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 80, 20));

        lblTotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTotal.setText("Total: ");
        visualVentas.add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 70, -1));

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel32.setText("Stock:");
        visualVentas.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, -1, -1));

        lblStockMedicamento.setBackground(new java.awt.Color(255, 255, 255));
        lblStockMedicamento.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblStockMedicamento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        visualVentas.add(lblStockMedicamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 90, 20));

        spCantidad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        visualVentas.add(spCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, 90, 20));

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel33.setText("Cantidad:");
        visualVentas.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, 70, -1));

        lblTotalPago.setBackground(new java.awt.Color(255, 255, 255));
        lblTotalPago.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        visualVentas.add(lblTotalPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, 80, 20));

        finalizarVenta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        finalizarVenta.setText("Finalizar Venta");
        finalizarVenta.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        finalizarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalizarVentaActionPerformed(evt);
            }
        });
        visualVentas.add(finalizarVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 480, 120, 20));

        agregarVenta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        agregarVenta.setText("Agregar");
        agregarVenta.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        agregarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarVentaActionPerformed(evt);
            }
        });
        visualVentas.add(agregarVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 70, 20));

        quitarMedicamento.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        quitarMedicamento.setText("Quitar Medicamento");
        quitarMedicamento.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        quitarMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitarMedicamentoActionPerformed(evt);
            }
        });
        visualVentas.add(quitarMedicamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 150, 20));

        cancelarVenta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cancelarVenta.setText("Cancelar Venta");
        cancelarVenta.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cancelarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarVentaActionPerformed(evt);
            }
        });
        visualVentas.add(cancelarVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 480, 120, 20));

        dniventaconf.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        dniventaconf.setForeground(new java.awt.Color(255, 0, 0));
        visualVentas.add(dniventaconf, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 180, 20));

        gestionVenta.add(visualVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 650, 540));

        jLabel59.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/org/farmanova/moduloatencion/presentation/icons/iconVenta.png"))); // NOI18N
        gestionVenta.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, -1));

        javax.swing.GroupLayout VentasLayout = new javax.swing.GroupLayout(Ventas);
        Ventas.setLayout(VentasLayout);
        VentasLayout.setHorizontalGroup(
            VentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gestionVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1717, Short.MAX_VALUE))
        );
        VentasLayout.setVerticalGroup(
            VentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentasLayout.createSequentialGroup()
                .addComponent(gestionVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1043, Short.MAX_VALUE))
        );

        Contenido.add(Ventas, "cardVentas");

        jPanel2.add(Contenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 0, -1, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 492;
        gridBagConstraints.ipady = 291;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(jPanel2, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerrarActionPerformed

        Sesion.cerrarSesion();
        LoginJFrame ventanaLogin = new LoginJFrame();
        ventanaLogin.setVisible(true);
        ventanaLogin.setLocationRelativeTo(null);
        this.dispose();

    }//GEN-LAST:event_botonCerrarActionPerformed

    private void botonTurnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTurnosActionPerformed
        java.awt.CardLayout layout = (java.awt.CardLayout) Contenido.getLayout();
        layout.show(Contenido, "cardTurnos");
    }//GEN-LAST:event_botonTurnosActionPerformed

    private void botonClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonClientesActionPerformed
        java.awt.CardLayout layout = (java.awt.CardLayout) Contenido.getLayout();
        layout.show(Contenido, "cardClientes");
    }//GEN-LAST:event_botonClientesActionPerformed

    private void botonVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVentasActionPerformed
        java.awt.CardLayout layout = (java.awt.CardLayout) Contenido.getLayout();
        layout.show(Contenido, "cardVentas");
    }//GEN-LAST:event_botonVentasActionPerformed

    private void botonNuevoTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevoTurnoActionPerformed
        java.awt.CardLayout layout = (java.awt.CardLayout) visualTurnos.getLayout();
        layout.show(visualTurnos, "cardNuevoTurno");
    }//GEN-LAST:event_botonNuevoTurnoActionPerformed

    private void botonAtenderTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAtenderTurnoActionPerformed
        java.awt.CardLayout layout = (java.awt.CardLayout) visualTurnos.getLayout();
        layout.show(visualTurnos, "cardAtenderTurno");
    }//GEN-LAST:event_botonAtenderTurnoActionPerformed

    private void cboFiltroEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboFiltroEstadoActionPerformed
        mostrarTablaTurnos();
    }//GEN-LAST:event_cboFiltroEstadoActionPerformed

    private void txtDniBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDniBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDniBuscarActionPerformed

    private void buscarDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarDniActionPerformed
        try {

            String dni = txtDniBuscar.getText().trim();

            if (dni.isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "Ingrese un DNI.");
                return;
            }

            if (dni.length() != 8) {
                JOptionPane.showMessageDialog(this,
                        "El DNI debe tener 8 dígitos.");
                return;
            }

            Cliente cliente = ClienteService.buscarCliente(dni);

            JOptionPane.showMessageDialog(this, cliente);
            txtDniBuscar.setText("");

        } catch (BusinessException ex) {

            JOptionPane.showMessageDialog(this, ex.getMessage());

        }
    }//GEN-LAST:event_buscarDniActionPerformed

    private void botonBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarClienteActionPerformed
        java.awt.CardLayout layout = (java.awt.CardLayout) visualClientes.getLayout();
        layout.show(visualClientes, "cardListaCliente");
    }//GEN-LAST:event_botonBuscarClienteActionPerformed

    private void agregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarClienteActionPerformed

        String nombre = NombreCliente.getText().trim();
        String apellido = ApellidoCliente.getText().trim();
        String dni = DNICliente.getText().trim();
        String telefono = TelefonoCliente.getText().trim();

        if (nombre.isBlank()) {
            JOptionPane.showMessageDialog(this, "Ingrese el nombre.");
            return;
        }

        if (apellido.isBlank()) {
            JOptionPane.showMessageDialog(this, "Ingrese el apellido.");
            return;
        }

        if (dni.length() != 8) {
            JOptionPane.showMessageDialog(this, "El DNI debe tener 8 dígitos.");
            return;
        }

        if (telefono.length() != 9) {
            JOptionPane.showMessageDialog(this, "El teléfono debe tener 9 dígitos.");
            return;
        }

        if (!telefono.startsWith("9")) {
            JOptionPane.showMessageDialog(this, "El teléfono debe comenzar con el número 9.");
            return;
        }

        try {

            ClienteService.registrarCliente(
                    dni,
                    nombre,
                    apellido,
                    telefono
            );

            JOptionPane.showMessageDialog(this,
                    "Cliente registrado correctamente.");

            cargarTablaCliente();
            limpiarFormularioClientes();

        } catch (BusinessException ex) {

            JOptionPane.showMessageDialog(
                    this,
                    ex.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );

        }
    }//GEN-LAST:event_agregarClienteActionPerformed

    private void botonNuevoCliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevoCliente1ActionPerformed
        java.awt.CardLayout layout = (java.awt.CardLayout) visualClientes.getLayout();
        layout.show(visualClientes, "cardNuevoCliente");
    }//GEN-LAST:event_botonNuevoCliente1ActionPerformed

    private void crearTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearTurnoActionPerformed
        try {

            String dni = txtDni.getText().trim();

            if (dni.isEmpty()) {

                JOptionPane.showMessageDialog(this,
                        "Ingrese un DNI.");
                return;

            }

            if (dni.length() != 8) {

                JOptionPane.showMessageDialog(this,
                        "El DNI debe tener 8 dígitos.");
                return;

            }

            Cliente cliente = ClienteService.buscarCliente(dni);

            int dia = Integer.parseInt(cboDia.getSelectedItem().toString());
            int mes = Integer.parseInt(cboMes.getSelectedItem().toString());
            int anio = Integer.parseInt(cboAnio.getSelectedItem().toString());

            LocalDate fecha = LocalDate.of(anio, mes, dia);

            LocalTime hora = LocalTime.parse(cboHora.getSelectedItem().toString());

            PrioridadTurno prioridad = PrioridadTurno.valueOf(cboPrioridad.getSelectedItem().toString());

            TurnoService.registrarTurno(cliente, fecha, hora, prioridad);

            JOptionPane.showMessageDialog(this, "Turno registrado.");

            actualizarHistorial();
            actualizarCola();

            limpiarFormularioTurnos();

        } catch (DateTimeException e) {

            JOptionPane.showMessageDialog(this,
                    "La fecha seleccionada no es válida.");

        } catch (BusinessException ex) {
            JOptionPane.showMessageDialog(
                    this,
                    ex.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_crearTurnoActionPerformed

    private void atenderTurnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atenderTurnosActionPerformed
        try {

            int opcion = JOptionPane.showConfirmDialog(
                    this,
                    "¿Desea atender el siguiente turno?",
                    "Confirmar",
                    JOptionPane.YES_NO_OPTION
            );

            if (opcion != JOptionPane.YES_OPTION) {
                return;
            }

            Turno turno = TurnoService.atenderSiguienteTurno();

            JOptionPane.showMessageDialog(this,
                    "Turno atendido correctamente.\n\n"
                    + turno);

            actualizarHistorial();      // Historial
            actualizarCola();  // Cola

        } catch (BusinessException ex) {

            JOptionPane.showMessageDialog(this,
                    ex.getMessage());

        }
    }//GEN-LAST:event_atenderTurnosActionPerformed

    private void cancelarTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarTurnoActionPerformed
        try {

            int opcion = JOptionPane.showConfirmDialog(
                    this,
                    "¿Seguro de marcar el turno como NO VINO?",
                    "Confirmar",
                    JOptionPane.YES_NO_OPTION
            );

            if (opcion != JOptionPane.YES_OPTION) {
                return;
            }

            Turno turno = TurnoService.marcarNoVino();

            JOptionPane.showMessageDialog(this,
                    "Turno cancelado - No Vino.\n\n"
                    + turno);

            actualizarHistorial();
            actualizarCola();

        } catch (BusinessException ex) {

            JOptionPane.showMessageDialog(this,
                    ex.getMessage());

        }
    }//GEN-LAST:event_cancelarTurnoActionPerformed

    private void btnBuscarMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarMedicamentoActionPerformed
        try {

            String texto = txtCodigoMedicamento.getText().trim();

            if (texto.isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "Ingrese un código.");
                return;
            }

            int codigo = Integer.parseInt(texto);

            Medicamento m = MedicamentoService.buscarMedicamento(codigo);

            JOptionPane.showMessageDialog(this,
                    "Código: " + m.getId()
                    + "\nNombre: " + m.getNombre()
                    + "\nLaboratorio: " + m.getLaboratorio()
                    + "\nPrecio: S/ " + m.getPrecio()
                    + "\nStock: " + m.getStock()
                    + "\nVence: " + m.getFechaVencimiento());

            txtCodigoMedicamento.setText("");

        } catch (NumberFormatException ex) {

            JOptionPane.showMessageDialog(this,
                    "Ingrese un código válido.");

        } catch (BusinessException ex) {

            JOptionPane.showMessageDialog(this,
                    ex.getMessage());

        }
    }//GEN-LAST:event_btnBuscarMedicamentoActionPerformed

    private void txtCodigoMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoMedicamentoActionPerformed
    }//GEN-LAST:event_txtCodigoMedicamentoActionPerformed

    private void botonMedicamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMedicamentosActionPerformed
        java.awt.CardLayout layout = (java.awt.CardLayout) Contenido.getLayout();
        layout.show(Contenido, "cardMedicamentos");
    }//GEN-LAST:event_botonMedicamentosActionPerformed

    private void quitarMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitarMedicamentoActionPerformed

        try {

            if (ventaActual == null) {
                throw new BusinessException("No hay una venta en proceso.");
            }

            int fila = tblDetalleVenta.getSelectedRow();

            if (fila == -1) {
                throw new BusinessException("Seleccione un medicamento.");
            }

            int opcion = JOptionPane.showConfirmDialog(
                    this,
                    "¿Desea quitar el medicamento seleccionado?",
                    "Confirmar",
                    JOptionPane.YES_NO_OPTION
            );

            if (opcion != JOptionPane.YES_OPTION) {
                return;
            }

            VentaService.quitarDetalle(
                    ventaActual,
                    fila
            );

            llenarTabla();

            actualizarTotal();

        } catch (BusinessException ex) {

            JOptionPane.showMessageDialog(
                    this,
                    ex.getMessage()
            );

        }
    }//GEN-LAST:event_quitarMedicamentoActionPerformed

    private void agregarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarVentaActionPerformed
        try {

            if (ventaActual == null) {
                throw new BusinessException("Primero debe buscar un cliente.");
            }

            if (medicamentoActual == null) {
                throw new BusinessException("Primero debe buscar un medicamento.");
            }

            int cantidad = (Integer) spCantidad.getValue();

            if (cantidad <= 0) {
                JOptionPane.showMessageDialog(this,
                        "Ingrese una cantidad válida.");
                return;
            }

            VentaService.agregarDetalle(ventaActual, medicamentoActual, cantidad);

            llenarTabla();

            actualizarTotal();

            limpiarMedicamento();

            spCantidad.setValue(1);

        } catch (BusinessException ex) {

            JOptionPane.showMessageDialog(
                    this,
                    ex.getMessage()
            );

        }
    }//GEN-LAST:event_agregarVentaActionPerformed

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
        try {

            String dni = txtDniCliente.getText().trim();

            if (dni.isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "Ingrese un DNI.");
                txtDniCliente.requestFocus();
                return;
            }

            if (dni.length() != 8) {
                JOptionPane.showMessageDialog(this,
                        "El DNI debe tener 8 dígitos.");
                txtDniCliente.requestFocus();
                return;
            }

            clienteVenta = ClienteService.buscarCliente(dni);

            lblNombreCliente.setText(
                    clienteVenta.getNombre() + " " + clienteVenta.getApellido()
            );

            ventaActual = VentaService.crearVenta(
                    clienteVenta,
                    Sesion.getUsuarioActual()
            );

        } catch (BusinessException ex) {

            JOptionPane.showMessageDialog(
                    this,
                    ex.getMessage()
            );

        }


    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    private void btnBuscarMedicamento2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarMedicamento2ActionPerformed
        try {

            String texto = txtCodigo.getText().trim();

            if (texto.isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "Ingrese un código.");
                return;
            }

            int codigo = Integer.parseInt(texto);

            medicamentoActual = MedicamentoService.buscarMedicamento(codigo);

            lblNombreMedicamento.setText(
                    medicamentoActual.getNombre()
            );

            lblPrecioMedicamento.setText(
                    String.format("S/. %.2f",
                            medicamentoActual.getPrecio())
            );

            lblStockMedicamento.setText(
                    String.valueOf(
                            medicamentoActual.getStock())
            );

        } catch (NumberFormatException ex) {

            JOptionPane.showMessageDialog(
                    this,
                    "Ingrese un código válido."
            );

        } catch (BusinessException ex) {

            JOptionPane.showMessageDialog(
                    this,
                    ex.getMessage()
            );

        }
    }//GEN-LAST:event_btnBuscarMedicamento2ActionPerformed

    private void cancelarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarVentaActionPerformed
        if (ventaActual == null) {

            JOptionPane.showMessageDialog(
                    this,
                    "No hay una venta en proceso."
            );

            return;

        }

        int opcion = JOptionPane.showConfirmDialog(
                this,
                "¿Está seguro de cancelar la venta? Todo será borrado",
                "Confirmar",
                JOptionPane.YES_NO_OPTION
        );

        if (opcion != JOptionPane.YES_OPTION) {
            return;
        }

        limpiarFormulario();
    }//GEN-LAST:event_cancelarVentaActionPerformed

    private void finalizarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalizarVentaActionPerformed
        try {

            if (ventaActual == null) {
                throw new BusinessException("No hay una venta en proceso.");
            }

            int opcion = JOptionPane.showConfirmDialog(
                    this,
                    "¿Desea finalizar la venta?",
                    "Confirmar",
                    JOptionPane.YES_NO_OPTION
            );

            if (opcion != JOptionPane.YES_OPTION) {
                return;
            }

            VentaService.finalizarVenta(ventaActual);

            cargarTablaMedicamentos();

            JOptionPane.showMessageDialog(
                    this,
                    "Venta registrada correctamente."
            );

            limpiarFormulario();

        } catch (BusinessException ex) {

            JOptionPane.showMessageDialog(
                    this,
                    ex.getMessage()
            );

        }
    }//GEN-LAST:event_finalizarVentaActionPerformed

    private void txtDniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDniKeyTyped
        char c = evt.getKeyChar();

        lblErrorDni.setText("");

        if (!Character.isDigit(c) && !Character.isISOControl(c)) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
            lblErrorDni.setText("Solo se permiten números.");
            return;
        }

        if (txtDni.getText().length() >= 8 && Character.isDigit(c)) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
            lblErrorDni.setText("Ingrese un DNI correcto");
        }
    }//GEN-LAST:event_txtDniKeyTyped

    private void DNIClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DNIClienteKeyTyped
        char c = evt.getKeyChar();

        lblErrorDni2.setText("");

        if (!Character.isDigit(c) && !Character.isISOControl(c)) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
            lblErrorDni2.setText("Solo se permiten números.");
            return;
        }

        if (DNICliente.getText().length() >= 8 && Character.isDigit(c)) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
            lblErrorDni2.setText("Ingrese un DNI correcto");
        }
    }//GEN-LAST:event_DNIClienteKeyTyped

    private void TelefonoClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TelefonoClienteKeyTyped

        char c = evt.getKeyChar();

        lblErrorTelefono.setText("");

        if (!Character.isDigit(c) && !Character.isISOControl(c)) {

            evt.consume();
            Toolkit.getDefaultToolkit().beep();
            lblErrorTelefono.setText("Solo se permiten números.");
            return;

        }

        if (TelefonoCliente.getText().length() >= 9 && Character.isDigit(c)) {

            evt.consume();
            Toolkit.getDefaultToolkit().beep();
            lblErrorTelefono.setText("Ingrese un numero de télefono correcto");

        }
    }//GEN-LAST:event_TelefonoClienteKeyTyped

    private void txtDniClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDniClienteKeyTyped

        char c = evt.getKeyChar();

        dniventaconf.setText("");

        if (!Character.isDigit(c) && !Character.isISOControl(c)) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
            dniventaconf.setText("Solo se permiten números.");
            return;
        }

        if (txtDniCliente.getText().length() >= 8 && Character.isDigit(c)) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
            dniventaconf.setText("Ingrese un DNI Correcto");
        }
    }//GEN-LAST:event_txtDniClienteKeyTyped

    private void txtDniBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDniBuscarKeyTyped

        char c = evt.getKeyChar();

        lblerrorDniBuscar.setText("");

        if (!Character.isDigit(c) && !Character.isISOControl(c)) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
            lblerrorDniBuscar.setText("Solo se permiten números.");
            return;
        }

        if (txtDniBuscar.getText().length() >= 8 && Character.isDigit(c)) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
            lblerrorDniBuscar.setText("Ingrese un DNI Correcto");
        }
    }//GEN-LAST:event_txtDniBuscarKeyTyped

    private void buscarTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarTurnoActionPerformed
        try {

            String id = txtbuscarTurnoCodigo.getText().trim();

            if (id.isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "Ingrese un código.");
                return;
            }

            int codigo = Integer.parseInt(id);

            Turno t = TurnoService.buscarPorCodigo(codigo);

            JOptionPane.showMessageDialog(this,
                    "Código: " + t.getCodigo()
                    + "\nCliente: " + t.getCliente().getNombre() + " " + t.getCliente().getApellido()
                    + "\nFecha: " + t.getFecha()
                    + "\nHora:  " + t.getHora()
                    + "\nPrioridad: " + t.getPrioridad()
                    + "\nEstado: " + t.getEstado());

            txtbuscarTurnoCodigo.setText("");

        } catch (NumberFormatException ex) {

            JOptionPane.showMessageDialog(this,
                    "Ingrese un código válido.");

        } catch (BusinessException ex) {

            JOptionPane.showMessageDialog(this,
                    ex.getMessage());

        }

    }//GEN-LAST:event_buscarTurnoActionPerformed

        private void actualizarHistorial() {

            List<Turno> lista;

            String filtro = cboFiltroEstado.getSelectedItem().toString();

            if (filtro.equals("TODOS")) {

                lista = TurnoService.listarTurnos();

            } else {

                EstadoTurno estado = EstadoTurno.valueOf(filtro);

                lista = TurnoService.listarPorEstado(estado);

            }

            llenarTabla(lista);

        }

        private void actualizarCola() {
            List<Turno> lista = TurnoService.listarCola();
            llenarTablaCola(lista);
        }

        private void llenarTablaCola(List<Turno> lista) {
            DefaultTableModel modelo
                    = (DefaultTableModel) tblCola.getModel();

            modelo.setRowCount(0);
            for (Turno t : lista) {

                modelo.addRow(new Object[]{
                    t.getCodigo(),
                    t.getCliente().getNombre(),
                    t.getCliente().getDni(),
                    t.getPrioridad(),
                    t.getFecha(),
                    t.getHora()
                });

            }
        }

        private void llenarTabla(List<Turno> lista) {

            DefaultTableModel modelo
                    = (DefaultTableModel) tblTurnos.getModel();

            modelo.setRowCount(0);

            for (Turno t : lista) {

                modelo.addRow(new Object[]{
                    t.getCodigo(),
                    t.getCliente().getDni(),
                    t.getCliente().getNombre(),
                    t.getFecha(),
                    t.getHora(),
                    t.getPrioridad(),
                    t.getEstado()

                });

            }

        }

        private void limpiarFormularioClientes() {
            lblErrorDni2.setText("");
            lblErrorTelefono.setText("");
            NombreCliente.setText("");
            ApellidoCliente.setText("");
            DNICliente.setText("");
            TelefonoCliente.setText("");
        }

        private void limpiarFormularioTurnos() {
            lblErrorDni.setText("");
            txtDni.setText("");
            cboDia.setSelectedIndex(0);
            cboMes.setSelectedIndex(0);
            cboAnio.setSelectedIndex(0);
            cboHora.setSelectedIndex(0);
            cboPrioridad.setSelectedIndex(0);
            txtDni.requestFocus();

        }

        private void mostrarTablaTurnos() {

            CardLayout layout
                    = (CardLayout) visualTurnos.getLayout();

            layout.show(visualTurnos, "cardTabla");

            actualizarHistorial();

        }

        private void cargarTablaCliente() {
            DefaultTableModel modelo
                    = (DefaultTableModel) tblCliente.getModel();

            modelo.setRowCount(0);

            List<Cliente> clientes = ClienteService.listarClientes();

            for (Cliente c : clientes) {
                modelo.addRow(new Object[]{
                    c.getDni(),
                    c.getNombre(),
                    c.getApellido(),
                    c.getCelular()
                });
            }
        }

        private void cargarTablaMedicamentos() {

            DefaultTableModel modelo
                    = (DefaultTableModel) tblMedicamentos.getModel();

            modelo.setRowCount(0);

            List<Medicamento> lista
                    = MedicamentoService.listarMedicamentos();

            for (Medicamento m : lista) {

                modelo.addRow(new Object[]{
                    m.getId(),
                    m.getNombre(),
                    m.getLaboratorio(),
                    m.getPrecio(),
                    m.getStock(),
                    m.getFechaVencimiento()

                });

            }

        }

        private void limpiarFormulario() {
            clienteVenta = null;
            medicamentoActual = null;
            ventaActual = null;

            txtDniCliente.setText("");
            txtCodigo.setText("");

            lblNombreCliente.setText("");
            lblNombreMedicamento.setText("");
            lblPrecioMedicamento.setText("");
            lblStockMedicamento.setText("");

            spCantidad.setValue(1);

            lblTotalPago.setText("S/. 0.00");

            DefaultTableModel modelo = (DefaultTableModel) tblDetalleVenta.getModel();
            modelo.setRowCount(0);

            txtDniCliente.requestFocus();
        }

        private void llenarTabla() {
            DefaultTableModel modelo
                    = (DefaultTableModel) tblDetalleVenta.getModel();

            modelo.setRowCount(0);

            if (ventaActual == null) {
                return;
            }

            for (DetalleVenta detalle : ventaActual.getDetalles()) {

                modelo.addRow(new Object[]{
                    detalle.getMedicamento().getId(),
                    detalle.getMedicamento().getNombre(),
                    detalle.getPrecioUnitario(),
                    detalle.getCantidad(),
                    detalle.getSubtotal()
                });

            }
        }

        private void actualizarTotal() {

            if (ventaActual == null) {

                lblTotalPago.setText("S/. 0.00");
                return;

            }

            lblTotalPago.setText(
                    String.format("S/. %.2f",
                            ventaActual.getTotal())
            );

        }

        private void limpiarMedicamento() {

            medicamentoActual = null;

            txtCodigo.setText("");

            lblNombreMedicamento.setText("");
            lblPrecioMedicamento.setText("");
            lblStockMedicamento.setText("");

            spCantidad.setValue(1);

        }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ApellidoCliente;
    private javax.swing.JPanel Clientes;
    private javax.swing.JPanel Contenido;
    private javax.swing.JTextField DNICliente;
    private javax.swing.JPanel Medicamentos;
    private javax.swing.JTextField NombreCliente;
    private javax.swing.JPanel PanelTurnos;
    private javax.swing.JTextField TelefonoCliente;
    private javax.swing.JPanel Turnos;
    private javax.swing.JPanel Ventas;
    private javax.swing.JButton agregarCliente;
    private javax.swing.JButton agregarVenta;
    private javax.swing.JPanel atenderTurno;
    private javax.swing.JButton atenderTurnos;
    private javax.swing.JPanel barraNavegadora;
    private javax.swing.JButton botonAtenderTurno;
    private javax.swing.JButton botonBuscarCliente;
    private javax.swing.JButton botonCerrar;
    private javax.swing.JButton botonClientes;
    private javax.swing.JButton botonMedicamentos;
    private javax.swing.JButton botonNuevoCliente1;
    private javax.swing.JButton botonNuevoTurno;
    private javax.swing.JButton botonTurnos;
    private javax.swing.JButton botonVentas;
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnBuscarMedicamento;
    private javax.swing.JButton btnBuscarMedicamento2;
    private javax.swing.JButton buscarDni;
    private javax.swing.JToggleButton buscarTurno;
    private javax.swing.JButton cancelarTurno;
    private javax.swing.JButton cancelarVenta;
    private javax.swing.JComboBox<String> cboAnio;
    private javax.swing.JComboBox<String> cboDia;
    private javax.swing.JComboBox<String> cboFiltroEstado;
    private javax.swing.JComboBox<String> cboHora;
    private javax.swing.JComboBox<String> cboMes;
    private javax.swing.JComboBox<String> cboPrioridad;
    private javax.swing.JButton crearTurno;
    private javax.swing.JLabel dniventaconf;
    private javax.swing.JButton finalizarVenta;
    private javax.swing.JPanel gestionCliente;
    private javax.swing.JPanel gestionMedicamento;
    private javax.swing.JPanel gestionTurno;
    private javax.swing.JPanel gestionVenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JLabel lblCajero;
    private javax.swing.JLabel lblErrorDni;
    private javax.swing.JLabel lblErrorDni2;
    private javax.swing.JLabel lblErrorTelefono;
    private javax.swing.JLabel lblNombreCliente;
    private javax.swing.JLabel lblNombreMedicamento;
    private javax.swing.JLabel lblPrecioMedicamento;
    private javax.swing.JLabel lblStockMedicamento;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotalPago;
    private javax.swing.JLabel lblerrorDniBuscar;
    private javax.swing.JPanel listaClientes;
    private javax.swing.JPanel nuevoCliente;
    private javax.swing.JPanel nuevoTurno;
    private javax.swing.JButton quitarMedicamento;
    private javax.swing.JSpinner spCantidad;
    private javax.swing.JLabel subtítulo;
    private javax.swing.JTable tblCliente;
    private javax.swing.JTable tblCola;
    private javax.swing.JTable tblDetalleVenta;
    private javax.swing.JTable tblMedicamentos;
    private javax.swing.JTable tblTurnos;
    private javax.swing.JTextPane txtCodigo;
    private javax.swing.JTextField txtCodigoMedicamento;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtDniBuscar;
    private javax.swing.JTextPane txtDniCliente;
    private javax.swing.JTextPane txtbuscarTurnoCodigo;
    private javax.swing.JLabel título;
    private javax.swing.JPanel visualClientes;
    private javax.swing.JPanel visualMedicamentos;
    private javax.swing.JPanel visualTurnos;
    private javax.swing.JPanel visualVentas;
    // End of variables declaration//GEN-END:variables
}
