/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pe.org.farmanova.moduloatencion.presentation.JFrame;

import javax.swing.JOptionPane;
import pe.org.farmanova.moduloatencion.business.entities.Usuario;
import pe.org.farmanova.moduloatencion.business.sesion.Sesion;
import pe.org.farmanova.moduloatencion.service.BusinessException;
import pe.org.farmanova.moduloatencion.service.UsuarioService;

/**
 *
 * @author eliza
 */
public class LoginJFrame extends javax.swing.JFrame {


    /**
     * Creates new form LoginJFrame
     */
    public LoginJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        // Aplica un borde de sombra moderno con esquinas redondeadas coincidentes (arc: 15)
        jPanel1.setBorder(new com.formdev.flatlaf.ui.FlatDropShadowBorder(
            java.awt.Color.BLACK, // Color base de la sombra
            new java.awt.Insets(0, 0, 6, 6), // Extensión de la sombra (Derecha e Inferior)
            0.15f // Opacidad de la sombra (0.15 significa 15% de transparencia para que sea suave)
        ));
        cajaUsuario = new javax.swing.JTextField();
        cajaConstrasenia = new javax.swing.JPasswordField();
        botonLogin = new javax.swing.JButton();
        titulo = new javax.swing.JLabel();
        indicador1 = new javax.swing.JLabel();
        contrasenia = new javax.swing.JLabel();
        usuario = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setMaximumSize(new java.awt.Dimension(400, 660));
        jPanel1.setName(""); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cajaUsuario.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        cajaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(cajaUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 310, -1));

        cajaConstrasenia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cajaConstraseniaMousePressed(evt);
            }
        });
        cajaConstrasenia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaConstraseniaActionPerformed(evt);
            }
        });
        jPanel1.add(cajaConstrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 310, -1));

        botonLogin.setBackground(new java.awt.Color(0, 115, 230));
        botonLogin.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        botonLogin.setForeground(new java.awt.Color(255, 255, 255));
        botonLogin.setText("Iniciar Sesion");
        botonLogin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLoginActionPerformed(evt);
            }
        });
        jPanel1.add(botonLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 310, 30));

        titulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titulo.setForeground(new java.awt.Color(0, 115, 230));
        titulo.setText("Farmanova");
        jPanel1.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, -1, -1));

        indicador1.setText("Ingresa tus credenciales para acceder al sistema");
        jPanel1.add(indicador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        contrasenia.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        contrasenia.setForeground(new java.awt.Color(62, 77, 91));
        contrasenia.setText("Contraseña");
        jPanel1.add(contrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        usuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        usuario.setForeground(new java.awt.Color(62, 77, 91));
        usuario.setText("Usuario");
        jPanel1.add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, 30));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 115, 230));
        jButton1.setText("SALIR");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 640, 50, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/org/farmanova/moduloatencion/presentation/icons/iconPantalla.png"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 255)));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 360, 210));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/org/farmanova/moduloatencion/presentation/icons/iconFarmacia.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 100, 100));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 18;
        gridBagConstraints.ipady = 55;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 6);
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLoginActionPerformed
        try {

            String usuarios = cajaUsuario.getText().trim();
            String password = new String(cajaConstrasenia.getPassword());

            Usuario u = UsuarioService.login(usuarios, password);
            Sesion.setUsuarioActual(u);

            switch (u.getRol()) {

                case ADMINISTRADOR -> {

                    AdministradorJFrame admin = new AdministradorJFrame();
                    admin.setLocationRelativeTo(null);
                    admin.setVisible(true);

                }

                case CAJERO -> {

                    CajeroJFrame cajero = new CajeroJFrame();
                    cajero.setLocationRelativeTo(null);
                    cajero.setVisible(true);

                }

            }

            dispose();

        } catch (BusinessException ex) {

            JOptionPane.showMessageDialog(this, ex.getMessage());

        }

    }//GEN-LAST:event_botonLoginActionPerformed

    private void cajaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaUsuarioActionPerformed

    private void cajaConstraseniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaConstraseniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaConstraseniaActionPerformed

    private void cajaConstraseniaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cajaConstraseniaMousePressed
        cajaConstrasenia.requestFocusInWindow();
    }//GEN-LAST:event_cajaConstraseniaMousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        javax.swing.JOptionPane.showMessageDialog(this, "Hasta luego!!");
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonLogin;
    private javax.swing.JPasswordField cajaConstrasenia;
    private javax.swing.JTextField cajaUsuario;
    private javax.swing.JLabel contrasenia;
    private javax.swing.JLabel indicador1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel usuario;
    // End of variables declaration//GEN-END:variables
}
